Add skeleton code suggested by gpt4 - build failure
Commented/removed modules it half-defined

Causes linker failure!

```
   Compiling party_invites v0.1.0 (/home/tim/repo/party_invites)
error: linking with `cc` failed: exit status: 1
...
  = note: /usr/bin/ld: cannot find -lpq
          collect2: error: ld returned 1 exit status

error: could not compile `party_invites` (bin "party_invites") due to previous error

```